/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  webApiSideBar: [{type: 'autogenerated', dirName: 'web-api'}],
  jsApiSideBar: [{type: 'autogenerated', dirName: 'js-api'}],
  integrationsSideBar: [{type: 'autogenerated', dirName: 'integrations'}],
  otherSideBar: [{type: 'autogenerated', dirName: 'other'}]

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorissal',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Tutorissal2',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
};

module.exports = sidebars;
